### ISSUE TITLE
How can we restrict visibility of OpenShift-hosted apps to internal (SPAN/Gov) users only?

### ISSUE THREAD

**Issue by sheaphillips** [BCDevOps/issues-and-solutions#1]
Looking for a solution to allow certain apps/routes hosted on OpenShift to be visible to internal bc government users (e.g. SPANBC network) users only.

Current hypothesis is that we can do this via use of hostnames that only resolve with SPAN/internal DNS.  I am exploring this and will capture the result here or on the wiki.

Anyone else with thoughts/ideas/suggestions, please add in comments.

**Comment by watkinspd** [comment]
Like you can add kong to a pod to add API gateway functionality -->
Add a container to the pod that is a microservice style object that provides a type of gateway or vpn stop in front of your actual app. 
It would come with builtin integrations for siteminder, github, etc.  Switch the openshift route for your app to run thru the gateway container's service. Open the terminal window for that new gateway container thru the openshift webconsole and:
- curl the address for your actual app into the gateway service.
- curl in rules such as:  allow *, allow idir *, allow bceid *, allow 142.32.* etc, Nice would be a way to invite users to connect via an email link that they then can automatically associate their idir or bceid account to.

**Comment by sheaphillips** [comment]
that sounds cool, but for the first use case, we're going to get a wildcard
internal DNS entry for *.pathfinder.bcgov and use routes based on that that
will only resolve when on gov network which will achieve what's needed for
now.
ᐧ

**Comment by ll911** [comment]
I started several *.bcgov internal sites within DataBC, there are few issues we should be aware of this approach. 
1, *.bcgov is not a standard URL, some browser may not work directly without http:// or https:// prefix
2, since *.bcgov is an internal URL, public CA entrust cannot signed the internal SSL certs, unless we are going to have an enterprise level CA to sign the *.bcgov domain, you will get the browser warning for all self-signed the SSL certs.

if we have a Gateway, we can simply apply ACL to those non-public URL. e.g internal.pathfinder.gov.bc.ca
