### ISSUE TITLE
Template for Docker strategy build using code sourced from git repo

### ISSUE THREAD

**Issue by watkinspd** [BCDevOps/issues-and-solutions#2]
There should be a instant-app type template that specifies a Docker build strategy and uses the Dockerfile and other application files from a git repo.

Scenario:
 - I have a github repo containing my app and a Dockerfile 
- to spin the app at pathfinder all I want to do is pick a  "docker-git-repo" template from the catalog and paste the link to my git repo, specifiy the options for the route and such
- the model should be like the one for the current nodejs template, but rather than depend on the redhat image for node, simpler to switch to a docker strategy and build from docker file

**Comment by f-w** [comment]
Closest workaround for now is CLI `oc new-app`, but I can create such template.

**Comment by f-w** [comment]
I have created the [template](https://github.com/BCDevOps/templates/blob/master/dockerfile-over-git.yaml) and tested successfully to deploy [bca-api](https://github.com/bcdevexchange/bca-api). To use it, copy the yaml file to your local folder and run
```
oc create -f dockerfile-over-git.yaml
```
for updating existing template, run
```
oc replace -f dockerfile-over-git.yaml
```
instead.

There are several imperfections/caveats due to limited programbility within a template:
1. Not only you have to specify git URL of Dockerfile, you have to redundantly specify builder image and tag which is in the FROM clause of Dockerfile.
2. OpenShift cannot convert a parameter from string to number or vice versa (see openshift/origin#3496) so not only I cannot obtain what port the docker exposing the service by parsing the Dockerfile, but I cannot even ask user to enter it as parameter either. As a result, I have to hard code it to 8080. If this is incorrect for your Dockerfile, you have to change it in the runtime service instance after launch.
